name: dummytest
description: Gadgetmartbnp - Inventory and Sales Management System
#author: Shreyash Nepal shreyashnepal78@gmail.com
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  fluttertoast: ^8.0.9
  firebase_core: ^2.27.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.9.0

  file_picker: ^5.2.2
  image_picker: ^0.8.7+4
  path_provider: ^2.0.10
  provider: ^6.0.3

  flutter_speed_dial: ^6.0.0
  google_fonts: ^4.0.3
  shimmer: ^2.0.0
  lottie: ^2.2.0
  url_launcher: ^6.1.11
  archive: ^3.3.7

dependency_overrides:
  firebase_core_web: ^2.8.1
  firebase_auth_web: ^5.9.1
  firebase_storage_web: ^3.6.23
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/profitinventory.png"
flutter:

  uses-material-design: true
  assets:
  - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf