// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpR8Ep0qsaUff0mhyTrhnOcF2cMYVECR0',
    appId: '1:588473404651:web:cddd33d4cb861fd9b882ae',
    messagingSenderId: '588473404651',
    projectId: 'gadgetmart-5726d',
    authDomain: 'gadgetmart-5726d.firebaseapp.com',
    storageBucket: 'gadgetmart-5726d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXGdxU9f_908f0ANxH8yWevjrB1Qdjv8',
    appId: '1:588473404651:android:fcb8217d244030a8b882ae',
    messagingSenderId: '588473404651',
    projectId: 'gadgetmart-5726d',
    storageBucket: 'gadgetmart-5726d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfRXTmqti52_3LSbTRP21pOQ-uflQ56M',
    appId: '1:588473404651:ios:1193f1a722c718a9b882ae',
    messagingSenderId: '588473404651',
    projectId: 'gadgetmart-5726d',
    storageBucket: 'gadgetmart-5726d.firebasestorage.app',
    iosBundleId: 'com.example.dummytest',
  );
}
